### ISSUE TITLE
Error with Paper Spigot 1.12, using PWP.

### ISSUE THREAD

**Issue by TheIntelloBox** [AcmeProject/Gender#4]
[12:43:32] [Async Chat Thread - #25/ERROR]: **** THIS IS NOT AN ISSUE TO DO WITH PER WORLD PLUGINS ****
Could not pass event AsyncPlayerChatEvent to Gender v1.3.5b
org.bukkit.event.EventException: null
	at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:122) ~[?:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1329]
	at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:24) ~[patched_1.12.2.jar:git-Paper-1329]
	at us.Myles.PWP.TransparentListeners.PWPTimedRegisteredListener.callEvent(PWPTimedRegisteredListener.java:30) [PerWorldPlugins.jar:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) [patched_1.12.2.jar:git-Paper-1329]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:497) [patched_1.12.2.jar:git-Paper-1329]
	at net.minecraft.server.v1_12_R1.PlayerConnection.chat(PlayerConnection.java:1387) [patched_1.12.2.jar:git-Paper-1329]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1302) [patched_1.12.2.jar:git-Paper-1329]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [patched_1.12.2.jar:git-Paper-1329]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_72]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.NullPointerException

**Comment by LaxWasHere** [comment]
Fixed in b3eea8d862a165f9c5a456a05298c44e9102cdf1
